### PR TITLE
Configure assets only if sprockets are in use

### PR DESCRIPTION
**Pull request by lunich**
Closes https://github.com/hotwired/stimulus-rails/issues/48

### CODE REVIEW

**Comment by adrianthedev** [comment]
This does look good to go.
If `Rails.application.config` doesn't respond to `assets` Rails won't try to configure them.

Users have to go out of their way and require sprockets even if they don't use it to be able to install https://github.com/avo-hq/avo.

**Comment by airblade** [comment]
The [equivalent change in turbo-rails](https://github.com/hotwired/turbo-rails/commit/4e62efb435a2a05774bab857154ff1303331db8a) has already been merged.

It would be great if this were merged too :)

**Comment by airblade** [comment]
In the meantime, I added this initializer to my Rails app to hack around the problem.

```ruby
# config/initializers/stimulus.rb

config = Rails.application.config

def config.respond_to?(symbol, include_all=false)
  if symbol == :assets && caller[0] =~ %r{stimulus/engine}
    raise 'Check whether this hack can be removed.'
  end
  super
end

class AcceptAllMethodCalls < Object
  def method_missing(m, *a, &b)
    self
  end
end

def config.assets
  AcceptAllMethodCalls.new
end
```

**Comment by adrianthedev** [comment]
Hey @aldent95. Have a look at [this](https://github.com/hotwired/stimulus-rails/pull/60#issuecomment-845975775) hack around the problem 👆

**Comment by alanq** [comment]
The hack worked for me initially but now `ruby-3.0.0/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:201:in join: can't convert AcceptAllMethodCalls to String (AcceptAllMethodCalls#to_str gives AcceptAllMethodCalls) (TypeError)`

Even though` require "sprockets/railtie" `is commented out.

**Comment by yourtallness** [comment]
Maybe assign a reviewer or mention a maintainer? (Whichever is acceptable)

**Comment by lunich** [comment]
> Any way we can get more attention to this PR to get it merged?

> Maybe assign a reviewer or mention a maintainer? (Whichever is acceptable)

@dhh it a small fix but solves one pretty annoying issue. Is it possible to review this one and merge if it makes sense?

**Comment by airblade** [comment]
@dhh Thank you.

**Pull request merged**
