### PR TITLE
Experiment with a standard library of controllers

### PR DESCRIPTION
**Pull request by dhh**

### CODE REVIEW

**Comment by guillaumebriday** [comment]
Hi @dhh 

I created a stimulus library with bunch of Stimulus controller with a first class integration with Rails.

You might want to take a look at it: https://stimulus-components.netlify.app/docs/components/index/

**Comment by dhh** [comment]
Oh nice! Let's definitely collaborate on this. What I want to have with the standard library is that it's simply available without any additional work. You just start using the controller, and boom, it's there. With the in-browser ESM + sprockets approach, there's no added weight in your app for controllers you don't use.

**Comment by n4cr** [comment]
@dhh Would this be only in stimulus rails? It would be great if we can use it in non-rails projects too.

**Comment by dhh** [comment]
Oh for sure. We'd make this part of a JS package. Just using this branch as a way to spike the idea.

**Comment by jacobdaddario** [comment]
Is there a location or place that we could contribute ideas for a potential standard library? I feel that controllers that implement the `disable-with` and `data-confirm` behavior would be welcome, as I've seen a few people asking about them on the Hotwire discourse.

**Comment by dhh** [comment]
Would love to see a reimplementation of those too! If you want to take a stab, feel free to open a PR against this branch 👍

**Comment by swanson** [comment]
More suggestions/ideas: 

- the beacon controller from HEY seems neat (and maybe would expose the need for Rails CSRF helper?) 
- the callout controller from the Hotwire docs (maybe not that useful for application development, but nice for marketing sites/blogs, see: https://github.com/hotwired/stimulus-site/blob/main/_js/controllers/callout_controller.js)
- something to handle basic focus (`autofocus_first_element` from HEY maybe)
- something to highlight an element on the page (ala old-school `$.highlight()`)
- something for basic disabling/enabling form sections/elements (I have some code for this, but it's...not the cleanest)
- "dropzone" behavior (show an element or change class) when dragging over an area (might not be generic enough as you presumably want to do something when dropped)

**Comment by ghiculescu** [comment]
Confirm controller (similar to rails-ujs) would be handy.

```js
// app/javascript/controllers/confirmation_controller.js

import { Controller } from "stimulus"

export default class extends Controller {
  static values = { message: String }

  confirm(event) {
    if (!(window.confirm(this.messageValue))) {
      event.preventDefault()
    }
  }
}
```

Usage:

```erb
<%= button_to foo_path,
method: :delete,
form: { data: { controller: "confirmation", confirmation_message_value: "Are you sure you want to delete this?", action: "submit->confirmation#confirm" } } %>
```

**Comment by seb-jean** [comment]
I love this idea!

**Comment by brenogazzola** [comment]
We have one we call `util_controller` that we use pretty much everywhere and has 3 actions:
1 - Remove an element from the DOM
2 - Toggle an attribute in one or more elements (usually `disabled`)
3 - Toggle a class in one or more elements (usually `hidden`)

They take multiple targets which can be `this`, `parent`, `closest` or a valid `selector`. Example:
```
data: { action: "input->util#removeClass", target: ".btn-submit", class: "hidden" }
```

https://gist.github.com/brenogazzola/6be19aa88088fe1e25e740ad234d1706

**Pull request closed without merging**
