### PR TITLE
Autoloader improvements

### LINKED ISSUE #12: Autoloader eats errors
Since work is currently being done on the autoloader (#3, #11) I thought I'd ask - any interest in letting autoloader errors just happen?

The autoloader transforms import errors into a "Failed to autoload controller: ..." message. While writing a stimulus controller, I made a `SyntaxError` by importing a wrong module name, and had to stick a debugger into [the catch statement](https://github.com/hotwired/stimulus-rails/blob/83d678e71dd6562263ba5f219f14fe4a22e59d64/app/assets/javascripts/stimulus/loaders/autoloader.js#L14) to dig it out.

IMHO if something fails to load, swallowing the error a) confuses development, and b) will almost certainly break something downstream anyways unless your controller was entirely cruft.

At the minimum, it should console.log the error, no?

### LINKED ISSUE #14: Autoloading skips over turbo-frame loaded content
Hi 👋 

I noticed that when I receive new HTML content in a turbo-frame element, my stimulus `connect()` method wasn't being called for a controller that wasn't previously referenced in the page.  When I refreshed the page, everything worked fine.  After doing a bit of investigation, I believe it's due to the autoloader only listening to the `turbo:load` event.

I'm happy to open a PR to fix this, but I'm not sure what the best approach is.  On the [turbo events](https://turbo.hotwire.dev/reference/events) page, there doesn't seem to be an event that is triggered after turbo-frame content is loaded into the DOM.

A thought I had for how to solve this is to use a mutation observer -- A cool side effect of that route is that if you just edited the DOM and added a `data-controller="mycontroller"` element, it should be picked up & autoloaded as well.  Not sure if there's edge cases there that I'm missing though (admittedly, I haven't yet used the MutationObserver API 😅 ).  Also, doesn't stimulus already have a mutation observer on the entire document tree?  Would it make more sense to just hook in there?

Has anyone else ran into this?  In the meantime, I can workaround by disabling autoloading 🙂 

Thanks!

### PR DESCRIPTION
**Pull request by jmalcic**
This PR makes two improvements to the autoloader: support for multiword controller names, and namespaced identifiers, which should bring feature parity with the webpack helper. Not sure if we need tests at this point (equivalent ones exist for the webpack helper).
<hr/>
I've since added a MutationObserver (based on work by @seanpdoyle in #11—thanks for your PR!), and also changed the logging so that underlying errors are now logged along with the error from the autoloader.
<hr/>
Resolves #14, resolves #12

### CODE REVIEW

**Comment by dhh** [comment]
Let's definitely add some tests for this. Thanks for adding this ✌️❤️

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/stimulus-rails/pull/11, and didn't realize this pull request existed.

@jmalcic I've borrowed some ideas from your work, added System Tests, and list you as a co-author.

**Comment by dhh** [comment]
Good stuff. Can we combine this with the mutation observer from #11? Need to autoload whenever the DOM is changed. Not just on turbo:load.

Also, if we're going to do the autoloader tests in JS, why do we need to add sqlite3?

Thanks for working on this!

**Comment by jmalcic** [comment]
> I've opened #11, and didn't realize this pull request existed.
> 
> @jmalcic I've borrowed some ideas from your work, added System Tests, and list you as a co-author.

> Good stuff. Can we combine this with the mutation observer from #11? Need to autoload whenever the DOM is changed. Not just on turbo:load.

Whoops didn't see this before pushing! 😅 I'm happy to incorporate these changes here too.

> Also, if we're going to do the autoloader tests in JS, why do we need to add sqlite3?

We would need if we continue to require Active Record indirectly below in the dummy app. I'm happy to make this more granular though.

https://github.com/hotwired/stimulus-rails/blob/648037990f38bba218dd792fb41ec230504ea6ae/test/dummy/config/application.rb#L8

**Comment by koheisg** [comment]
Thank you grate work!! I'm looking forward to merging this patch!!

I think this PR will allow you to test without adding it to the gemspec, so check it out!
https://github.com/hotwired/stimulus-rails/pull/5/files

**Comment by gahia** [comment]
Hi!

Would you think about introduce a change in the `ImportmapHelper` to just import files ending in '.js' instead skip only folders and those starting with '.'?

Not sure if all JS libraries end with a .js but so far all stimulus controllers do. And this change will be really helpful when you load folders with a mix of files (not only .js) like in [view_components with stimulus controllers](https://viewcomponent.org/#stimulus).

This is what happen when you include the components folder:

```
{
	"imports": {
		"stimulus": "/assets/stimulus/libraries/stimulus-dcca1023dd079a97692e855a18618fc4827389a09a23b23c4ea8916f65d46f09.js",
		".keep": "/components/.keep",
		"card.html": "/components/card.html.slim",
		"card": "/components/card.rb",
		"card_controller": "/components/card_controller-6fb9f06f02cc9b20d81deda74ee422fbfe0ca5bba001ea35b3ecb599612caca6.js"
	}
}

```

Thanks!!!

**Comment by jmalcic** [comment]
You'll see there are error messages coming up when running tests (but which don't cause failures), this is because of the autoloader instance started as a side effect of importing the module. We could make this cleaner by not starting the autoloader in its module.

**Comment by jmalcic** [comment]
One other thing: would it be an idea to fix #4 in this PR? We can presumably solve this by maintaining a list of loaded controllers, but I don't want this PR to become unmanageably big

**Comment by seanpdoyle** [comment]
Thanks for drafting this up @jmalcic!

The [hotwired/turbo](https://github.com/hotwired/turbo) repository uses [intern](https://theintern.io) for its JavaScript test suite.

Have you considered it as an alternative to introducing Karma.js here? I think consistency in the tooling across the projects would go a long way.

This changset is pretty large in scope compared to https://github.com/hotwired/stimulus-rails/pull/11. I wonder if there's middle ground between the two that can shrink the scope and still resolve the underlying issues? At a minimum, would it be possible to add System Test level coverage since it's crucial the the Rails-side helper and the Autoload.js integrate correctly?

**Comment by jmalcic** [comment]
> Thanks for drafting this up @jmalcic!
> 
> The [hotwired/turbo](https://github.com/hotwired/turbo) repository uses [intern](https://theintern.io) for its JavaScript test suite.
> 
> Have you considered it as an alternative to introducing Karma.js here? I think consistency in the tooling across the projects would go a long way.

I opted for Karma because [`@stimulus/test`](https://github.com/hotwired/stimulus/tree/v2.0.0/packages/@stimulus/test) has a useful `DOMTestCase` class, and for a small repo like this it seemed better not to maintain a dedicated base test case class. I did look at [`hotwired/turbo`](https://github.com/hotwired/turbo), which has a [similar test case class called `DOMTestCase`](https://github.com/hotwired/turbo/blob/c52d87c9426ebbbb735e9e8947b3cbdfde8a2a10/src/tests/helpers/dom_test_case.ts), but it isn't available to import. `DOMTestCase` in `@stimulus/test` is based on `qunit`, and so won't hook into `intern` as it would need to. If `DOMTestCase` in `hotwired/turbo` ever became available, I don't think it would be all that hard to swap one for the other—you would just need to tweak the assertions and call a different function to register the tests. But since all the tests for `hotwired/stimulus` use `karma` anyway, I don't really see a big consistency advantage of using `intern` over `karma`. I also couldn't work out an easy way to use importmaps with `intern`.

> This changset is pretty large in scope compared to #11. I wonder if there's middle ground between the two that can shrink the scope and still resolve the underlying issues?

I'm certainly open to that, but a lot of the changes are to enable unit testing.

> At a minimum, would it be possible to add System Test level coverage since it's crucial the the Rails-side helper and the Autoload.js integrate correctly?

I'm open to this, though that will make the changeset for this PR much bigger still.

**Comment by seanpdoyle** [comment]
Thanks for clarifying @jmalcic.

#11 introduces System Tests that drive Chrome through Selenium, and #3 introduces Karma to drive Chrome. In my opinion, with the gem's scope being Rails related, System Testing involves a smaller changeset for similar payoff, and is part and parcel with the Rails tooling ecosystem whereas Karma (or Intern) are third-parties and require additional architectural changes and dependencies.

The most important facet of this gem is its Rails integration. While there is certainly value in Karma providing more granular testing utilities in JavaScript, it can't provide the same level of fidelity and confidence as running a suite that exercises both Rail and JS since a suite would entirely outside of the Rails stack.

**Comment by gahia** [comment]
Sorry guys, I though was working over this PR, but I've missed something in the way. Can check #21.

Thanks!

**Comment by jmalcic** [comment]
@dhh I think I've implemented all of the requested changes, would be great to know next steps!

**Comment by dhh** [comment]
Sorry to leave this hanging. I think the core progress here is good, but after further consideration, we've come to the conclusion that autoloading should be part of Stimulus itself. At least the main triggering mechanism. So I'll let @sstephenson take a stab at that first, then we can return to how to integrate it into the Rails gem. ✌️❤️

**Comment by jmalcic** [comment]
Makes complete sense, thanks for following up! Closing this now.

**Comment by filipemendespi** [comment]
I would like to congratulate the team, for the work and ask about a behavior that I am having with the autoload.

My application so far uses hotwire only in one view and I only call a stimulus controller only in that view. However any view I access it tries to load a controller and generates this one in the browser console: `Failed to autoload controller: controller_name Error: Unable to resolve specifier 'controller_name'`.

This is a desired behavior, why should I return this message only when I used the controller in the rendered html, or am I wrong?

**Pull request closed without merging**
